### ISSUE TITLE
NutTroop Nue Stomp softlock

### ISSUE THREAD

**Issue by markyys** [abyssonym/vast_violence#3]
Seed number 8752 generates NutTroops in Mt. Myrneg which know Nue Stomp, and will use it apparently exclusively. When they do so it causes a graphical glitch with their sprite and the game gets stuck as soon as their attack lands.

See attached screenshot ![NutTroop Nue Stomp](https://user-images.githubusercontent.com/425684/116772932-3b918500-aa20-11eb-826a-ecbae5c8b425.PNG)

Fortunately, this can be worked around by running immediately, so it is not game-breaking.

**Comment by abyssonym** [comment]
They shouldn't be able to obtain Nue Stomp as of v3.2. Are you playing on an older version? If so, you may want to update.

**Comment by markyys** [comment]
I built it out of the latest master as of a few days ago. Looks like it's tagged as v2.1

**Comment by markyys** [comment]
Looks like I happened to try this a few days too early.
